import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useState, useEffect } from 'react';
import {MdLocationPin} from 'react-icons/md';
import { useCountdown } from '../src/hooks/useCountdown';
import ImgHeader from '/public/assets/nome-branco.png';

export default function Home() {
    const [day, hour, minute, second] = useCountdown('2023-09-02 14:00:00');
    const [daysRemaining, setDaysReamining] = useState(0);
    const [hoursRemaining, setHoursReamining] = useState(0);

    return (
        <div className="flex flex-col items-center">
            <Head>
                <title>Emanoel & Rosi - Casamento</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header className="w-full h-20 border-b-2 flex justify-center items-center fixed bg-[#cb6834]">
                <Image
                    src={ImgHeader}
                    alt='Imagem dos noivos'
                    className='w-[75px] object-contain'
                />  
            </header>

            <main className='flex flex-col items-center mt-24 px-3 bg-flores-1 bg-center'>
                <Image
                    src={require('../src/assets/img-site.png')}
                    alt='Imagem dos noivos'
                    className='w-[250px] h-[200px] object-cover border-4 border-[#cb6843] rounded-lg'
                />

                <p className="text-[#cb6843] text-center my-3">Estamos ansiosos esperando por você, confirme sua presença abaixo</p>
                <p className="text-[#cb6843] text-center">A festa será realizada no Victors Buffet, dia 2 de setembro às 11:30</p>
                <div className='flex items-center justify-center gap-1'>
                    <MdLocationPin color='black' size={25}/>
                    <p className='text-center'>R. Saldanha Marinho 259 - Santa Paula, São Caetano do Sul</p>
                </div>
                <h2 className="text-center font-bold text-xl mt-5">Faltam</h2>

                <div className="flex items-center justify-center gap-3">
                    <div className="flex flex-col items-center justify-center rounded-md gap-2 w-16 h-16 bg-[#cb6843]">
                        <p className="font-bold text-white text-3xl">{day}</p>
                        <p className="text-white text-sm mt-[-10px]">Dias</p>
                    </div>
                    <div className="flex flex-col items-center justify-center rounded-md gap-2 w-16 h-16 bg-[#cb6843]">
                        <p className="font-bold text-white text-3xl">{hour}</p>
                        <p className="text-white text-sm mt-[-10px]">Horas</p>
                    </div>
                    <div className="flex flex-col items-center justify-center rounded-md gap-2 w-16 h-16 bg-[#cb6843]">
                        <p className="font-bold text-white text-3xl">{minute}</p>
                        <p className="text-white text-sm mt-[-10px]">Minutos</p>
                    </div>
                    <div className="flex flex-col items-center justify-center rounded-md gap-2 w-16 h-16 bg-[#cb6843]">
                        <p className="font-bold text-white text-3xl">{second}</p>
                        <p className="text-white text-sm mt-[-10px]">Segundos</p>
                    </div>
                </div>

                <Link
                    href='/confirmation'
                    className='flex items-center justify-center rounded-3xl w-full font-bold text-white text-lg bg-[#cb6843] h-14 px-3 mt-7'
                >
                    Confirmar presença
                </Link>

                <h4 className="font-bold text-[#cb6843] mt-10">Quer nos presentear?</h4>
                <p className="text-black text-center">Fique a vontade para enviar qualquer valor de sua preferência</p>
            </main>

            <footer>
                
            </footer>
        </div>
    )
}
